### ISSUE TITLE
Feature Request: Missing Leaderboards

### ISSUE THREAD

**Issue by RatedFforFun** [bitbybyte/quarter-zone#3]
Hello, this is where the site said to submit feature requests so here I am!

Is the plan to eventually (not a priority now) incorporate all of the leaderboards within the game into Quarter Zone? I understand less people probably care about these but I would hope that a unified leaderboard website would cover everything the game offers, since this project is effectively doing what should have been done in the game.

Currently missing single player: Weekly Ritual Cont., Marathon (Endless), Master (Lines), All Clear PS4, Target PS4, Countdown (Endless), Mystery (Endless), All 6 Journey mode categories, The Zone*
Currently missing multiplayer: Connected VS (wins), Zone Battle (wins), Score Attack (wins), Classic Score Attack (wins)

*The Zone is covered in the hall of fame but not the full leaderboard.

**Comment by bitbybyte** [comment]
Connected wins are incorporated into each multiplayer leaderboard page.

Endless boards, Master (Lines), The Zone, and Journey boards were chosen to be excluded as they either 1) present a warped view of records relative to other platforms, or 2) have little competitive value as a leaderboard. This is open to change if more single player platforms are ingested. Steam players continue to see their records for these on their profile page.

PS4 boards cannot be scraped.

**Comment by bitbybyte** [comment]
Adding to this: Weekly Ritual is a transient board. In the future we may come up with a solution that aggregates each player's contribution, which might be more interesting than just refreshing the board every week.

**Comment by bitbybyte** [comment]
Hello again! I've chosen to include Journey total score and endless boards at this time. We'll continue to reasses with the others.

**Comment by RatedFforFun** [comment]
I've seen the changes. Looks good!
