### ISSUE TITLE
Journey Mode Leaderboard Mix Up

### ISSUE THREAD

**Issue by RatedFforFun** [bitbybyte/quarter-zone#4]
The Journey mode leaderboards are currently displaying the Area High Score leaderboards instead of the Total Score leaderboards. While some new players have added scores to the leaderboard since the last ingestion (some which may be cheated), there are enough perfectly matching scores that you can verify this mix up by simply cross referencing the top players scores in both leaderboards to what is on Quarter Zone.

For example: As of 10/27/2022, SGFerox has a 2,124,473 for Total Score and a 2,170,581 for Area High Score. Quarter Zone displays Total Score in the header of the page but shows SGFerox's 2,170,581. So either the scores are wrong or the header should be Area High Score.

**Comment by bitbybyte** [comment]
We've removed all single player boards from the site.
