### ISSUE TITLE
[Record Update]

### ISSUE THREAD

**Issue by andrew4043** [bitbybyte/quarter-zone#9]
Title: **[Record Update] {Ultra} - {man9948}**

Comment:

||Value|
|---------|-|
|Player|man9948|
|Score|65435|
|Date Achieved|2021|
|Platform|Xbox|
|Source|[https://cdn.discordapp.com/attachments/534518367034408980/908262701397049364/unknown.png](https://cdn.discordapp.com/attachments/534518367034408980/908262701397049364/unknown.png) |

**Comment by bitbybyte** [comment]
Closing this as we clarify how submissions will be used.
